spring:
  application:
    name: consumer
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
